<a href="https://colab.research.google.com/github/jsqzhu/BikeShareTO-ActiveAI/blob/main/BikeShare_EDA.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [3]:
import json
from dateutil.parser import parse
import pandas as pd
import numpy as np
import requests
import sys

#from parse_names import parseName, lookup
#from data_exceptions import missing_coordinates, location_rename, unknown_locations

In [17]:
# json file: https://tor.publicbikesystem.net/ube/gbfs/v1/en/station_information
url='https://raw.githubusercontent.com/jsqzhu/BikeShareTO-ActiveAI/main/station_information.json'
resp = requests.get(url)
station_info = json.loads(resp.text)

In [33]:
station_info_df = pd.json_normalize(station_info, record_path=['data','stations'])

In [34]:
station_info_df.head()

,station_id,name,physical_configuration,lat,lon,altitude,address,capacity,rental_methods,groups,obcn,nearby_distance,post_code,cross_street
0,7000,Fort York Blvd / Capreol Ct,REGULAR,43.639832,-79.395954,0.0,Fort York Blvd / Capreol Ct,35,"[KEY, TRANSITCARD, CREDITCARD, PHONE]",[],647-643-9607,500.0,NaN,NaN
1,7001,Wellesley Station Green P,REGULAR,43.664964,-79.383550,0.0,Yonge / Wellesley,17,"[KEY, TRANSITCARD, CREDITCARD, PHONE]",[],416-617-9576,500.0,M4Y 1G7,NaN
2,7002,St. George St / Bloor St W,REGULAR,43.667333,-79.399429,0.0,St. George St / Bloor St W,19,"[KEY, TRANSITCARD, CREDITCARD, PHONE]",[],647-643-9615,500.0,NaN,NaN
3,7003,Madison Ave / Bloor St W,REGULAR,43.667158,-79.402761,NaN,Madison Ave / Bloor St W,15,"[KEY, TRANSITCARD, CREDITCARD, PHONE]",[],647-631-4587,500.0,NaN,NaN
4,7004,University Ave / Elm St,REGULAR,43.656518,-79.389099,NaN,University Ave / Elm St,11,"[KEY, TRANSITCARD, CREDITCARD, PHONE]",[P7004-7047],647-643-9673,500.0,NaN,NaN